export const trip_match = {
  'ao-nang-krabi': ['koh-phi-phi', 'koh-lanta'],
  bangkok: [
    'koh-kood',
    'chiangmai',
    'koh-samet',
    'koh-chang',
    'pattaya',
    'koh-mak',
  ],
  chiangmai: ['pai', 'bangkok', 'mae-hong-son'],
  donsak: [
    'koh-samui',
    'koh-phangan',
    'trang',
    'suratthani',
    'nakhon-sri-thammarat',
    'khao-sok',
    'hat-yai',
  ],
  'hat-yai': ['koh-lipe'],
  'hua-hin': ['pattaya'],
  'koh-kood': ['bangkok'],
  'koh-lanta': [
    'krabi',
    'ao-nang-krabi',
    'koh-phi-phi',
    'phuket',
    'koh-bulone',
    'koh-lipe',
    'koh-kradan',
    'koh-mook',
    'koh-ngai',
  ],
  'koh-mak': ['bangkok'],
  'koh-phangan': [
    'koh-samui',
    'donsak',
    'suratthani',
    'khao-sok',
    'nakhon-sri-thammarat',
    'hat-yai',
    'trang',
  ],
  'koh-phi-phi': [
    'koh-lanta',
    'phuket',
    'koh-ngai',
    'koh-lipe',
    'koh-bulone',
    'krabi',
    'railay',
    'ao-nang-krabi',
    'koh-kradan',
    'koh-mook',
  ],
  'koh-samui': [
    'koh-phangan',
    'suratthani',
    'donsak',
    'nakhon-sri-thammarat',
    'khao-sok',
    'hat-yai',
    'trang',
  ],
  'koh-tao': ['koh-samui'],
  krabi: ['koh-phi-phi', 'koh-lanta', 'krabi', 'koh-phangan'],
  'nakhon-sri-thammarat': ['koh-samui', 'koh-phangan'],
  pattaya: ['koh-mak', 'bangkok', 'hua-hin'],
  phuket: [
    'koh-phi-phi',
    'koh-lanta',
    'koh-mook',
    'koh-kradan',
    'koh-bulone',
    'koh-lipe',
    'koh-ngai',
    'krabi',
  ],
  railay: ['koh-phi-phi'],
  satun: ['koh-bulone', 'koh-lipe'],
  suratthani: ['koh-samui', 'koh-phangan'],
  'koh-ngai': [
    'koh-lanta',
    'koh-kradan',
    'phuket',
    'koh-lipe',
    'koh-bulone',
    'koh-mook',
    'koh-phi-phi',
  ],
  'koh-mook': [
    'koh-bulone',
    'koh-kradan',
    'koh-lipe',
    'koh-lanta',
    'koh-ngai',
    'koh-phi-phi',
    'phuket',
  ],
  pai: ['chiangmai'],
  'mae-hong-son': ['chiangmai'],
  'koh-kradan': [
    'phuket',
    'koh-bulone',
    'koh-ngai',
    'koh-mook',
    'koh-lanta',
    'koh-lipe',
    'koh-phi-phi',
  ],
  'koh-bulone': [
    'koh-lanta',
    'koh-phi-phi',
    'satun',
    'langawi',
    'koh-kradan',
    'koh-lipe',
    'koh-ngai',
    'phuket',
    'koh-mook',
  ],
  'koh-lipe': [
    'satun',
    'hat-yai',
    'phuket',
    'koh-kradan',
    'koh-ngai',
    'koh-phi-phi',
    'koh-mook',
    'koh-lanta',
    'koh-bulone',
  ],
}
