export const destination_list = [
  {
    seed_key: 'ao-nang-krabi',
    name: 'Ao Nang Krabi',
    location_id: 1,
    location_type: 'destination',
    address: null,
    latitude: 8.0362834,
    longitude: 98.8328141,
    country: null,
  },
  {
    seed_key: 'bangkok',
    name: 'Bangkok',
    location_id: 3,
    location_type: 'destination',
    address: null,
    latitude: 13.7563309,
    longitude: 100.5017651,
    country: 'tha',
  },
  {
    seed_key: 'chiangmai',
    name: 'Chiangmai',
    location_id: 6,
    location_type: 'destination',
    address: null,
    latitude: 18.787747,
    longitude: 98.9931284,
    country: 'tha',
  },
  {
    seed_key: 'donsak',
    name: 'Donsak',
    location_id: 8,
    location_type: 'destination',
    address: null,
    latitude: 9.2823238,
    longitude: 99.7076122,
    country: 'tha',
  },
  {
    seed_key: 'hat-yai',
    name: 'Hat Yai',
    location_id: 9,
    location_type: 'destination',
    address: null,
    latitude: 7.0086472,
    longitude: 100.4746879,
    country: 'tha',
  },
  {
    seed_key: 'hua-hin',
    name: 'Hua Hin',
    location_id: 10,
    location_type: 'destination',
    address: null,
    latitude: 12.5683747,
    longitude: 99.9576888,
    country: 'tha',
  },
  {
    seed_key: 'khao-sok',
    name: 'Khao Sok',
    location_id: 13,
    location_type: 'destination',
    address: null,
    latitude: 8.9040783,
    longitude: 98.5233402,
    country: 'tha',
  },
  {
    seed_key: 'koh-chang',
    name: 'Koh Chang',
    location_id: 15,
    location_type: 'destination',
    address: null,
    latitude: 12.141329,
    longitude: 102.280469,
    country: 'tha',
  },
  {
    seed_key: 'koh-kood',
    name: 'Koh Kood',
    location_id: 17,
    location_type: 'destination',
    address: null,
    latitude: 11.6680759,
    longitude: 102.5642261,
    country: 'tha',
  },
  {
    seed_key: 'koh-lanta',
    name: 'Koh Lanta',
    location_id: 18,
    location_type: 'destination',
    address: 'Koh Lanta Krabi',
    latitude: 7.6243677,
    longitude: 99.0792263,
    country: 'tha',
  },
  {
    seed_key: 'koh-mak',
    name: 'Koh Mak',
    location_id: 19,
    location_type: 'destination',
    address: null,
    latitude: 11.822702,
    longitude: 102.4781873,
    country: 'tha',
  },
  {
    seed_key: 'koh-phangan',
    name: 'Koh Phangan',
    location_id: 20,
    location_type: 'destination',
    address: null,
    latitude: 9.7318753,
    longitude: 100.0135929,
    country: null,
  },
  {
    seed_key: 'koh-phi-phi',
    name: 'Koh Phi Phi',
    location_id: 21,
    location_type: 'destination',
    address: null,
    latitude: 7.738572,
    longitude: 98.770861,
    country: null,
  },
  {
    seed_key: 'koh-samet',
    name: 'Koh Samet',
    location_id: 22,
    location_type: 'destination',
    address: null,
    latitude: 12.5582501,
    longitude: 101.4510911,
    country: 'tha',
  },
  {
    seed_key: 'koh-samui',
    name: 'Koh Samui',
    location_id: 23,
    location_type: 'destination',
    address: null,
    latitude: 9.5595578,
    longitude: 99.9972839,
    country: 'tha',
  },
  {
    seed_key: 'koh-tao',
    name: 'Koh Tao',
    location_id: 24,
    location_type: 'destination',
    address: null,
    latitude: 10.0956102,
    longitude: 99.8403959,
    country: 'tha',
  },
  {
    seed_key: 'krabi',
    name: 'Krabi',
    location_id: 25,
    location_type: 'destination',
    address: null,
    latitude: 8.0862997,
    longitude: 98.9062835,
    country: 'tha',
  },
  {
    seed_key: 'langawi',
    name: 'Langkawi',
    location_id: 27,
    location_type: 'destination',
    address: null,
    latitude: 6.35,
    longitude: 99.8,
    country: 'tha',
  },
  {
    seed_key: 'nakhon-sri-thammarat',
    name: 'Nakhon Si Thammarat',
    location_id: 30,
    location_type: 'destination',
    address: null,
    latitude: 8.5400519,
    longitude: 99.940316,
    country: 'tha',
  },
  {
    seed_key: 'pattaya',
    name: 'Pattaya',
    location_id: 32,
    location_type: 'destination',
    address: null,
    latitude: 12.9276082,
    longitude: 100.8770813,
    country: 'tha',
  },
  {
    seed_key: 'phuket',
    name: 'Phuket',
    location_id: 38,
    location_type: 'destination',
    address: null,
    latitude: 7.9519331,
    longitude: 98.3380884,
    country: null,
  },
  {
    seed_key: 'railay',
    name: 'Railay Krabi',
    location_id: 40,
    location_type: 'destination',
    address: null,
    latitude: 8.0120253,
    longitude: 98.8373309,
    country: 'tha',
  },
  {
    seed_key: 'satun',
    name: 'Satun',
    location_id: 42,
    location_type: 'destination',
    address: null,
    latitude: 6.619641,
    longitude: 100.067298,
    country: 'tha',
  },
  {
    seed_key: 'suratthani',
    name: 'Surat Thani',
    location_id: 47,
    location_type: 'destination',
    address: null,
    latitude: 9.1342968,
    longitude: 99.142882,
    country: 'tha',
  },
  {
    seed_key: 'trang',
    name: 'Trang',
    location_id: 48,
    location_type: 'destination',
    address: null,
    latitude: 7.621347,
    longitude: 99.518001,
    country: 'tha',
  },
  {
    seed_key: 'koh-ngai',
    name: 'Koh Ngai',
    location_id: 427,
    location_type: 'destination',
    address: null,
    latitude: 7.416587,
    longitude: 99.203782,
    country: null,
  },
  {
    seed_key: 'koh-mook',
    name: 'Koh Mook',
    location_id: 428,
    location_type: 'destination',
    address: null,
    latitude: 7.373872,
    longitude: 99.305147,
    country: null,
  },
  {
    seed_key: 'pai',
    name: 'Pai',
    location_id: 434,
    location_type: 'destination',
    address: null,
    latitude: 19.35882,
    longitude: 98.439613,
    country: 'tha',
  },
  {
    seed_key: 'mae-hong-son',
    name: 'Mae Hong Son',
    location_id: 435,
    location_type: 'destination',
    address: null,
    latitude: 19.288127,
    longitude: 97.964566,
    country: 'tha',
  },
  {
    seed_key: 'koh-kradan',
    name: 'Koh Kradan',
    location_id: 762,
    location_type: 'destination',
    address: null,
    latitude: 7.311436,
    longitude: 99.257538,
    country: null,
  },
  {
    seed_key: 'koh-bulone',
    name: 'Koh Bulone',
    location_id: 763,
    location_type: 'destination',
    address: null,
    latitude: 6.826187,
    longitude: 99.536155,
    country: null,
  },
  {
    seed_key: 'koh-lipe',
    name: 'Koh Lipe',
    location_id: 777,
    location_type: 'destination',
    address: null,
    latitude: 6.488715,
    longitude: 99.304855,
    country: null,
  },
]
