export const learnCookingPlaylists = {
  image_url: 'thumb_frencfried.jpg',
  title: 'มึงว่ากูอ้วนยังวะ',
  lists: [
    {
      name: 'มันฝรั่งทอดจาก',
      instructor: 'กับข้าวกับตา',
      theme: {
        style: 'dark',
        color: 'dark-gray',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_snack.png',
      },
    },
    {
      name: 'วิธีทำป็อปคอร์นเม',
      instructor: 'WannabeMajor',
      theme: {
        style: 'dark',
        color: 'focus-orange',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_popcorn.png',
      },
    },
    {
      name: 'แป้งพิซซ่าอย่างง่าย',
      instructor: 'ItalianKitchen',
      theme: {
        style: 'dark',
        color: 'primary',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_pizza.png',
      },
    },
    {
      name: 'หวานเย็นจาก',
      instructor: 'coldddd',
      theme: {
        style: 'light',
        color: 'light-yellow',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_pine_apple.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
    {
      name: 'ไอศครีมโฮมเมด',
      instructor: 'coldddd',
      theme: {
        style: 'dark',
        color: 'black-pink',
      },
      view: 2000,
      rating: 4.4,
      media: {
        type: 'vdo',
        duration: 13,
        url: 'https://www.youtube.com/watch?v=ZJy1ajvMU1k',
        thumbnail: 'thumb_icecream.png',
      },
    },
  ],
}
